##########################################################################################################################
# File automatically-generated by tool: [projectgenerator] version: [3.17.1] date: [Mon Jul 18 09:45:33 CST 2022] 
##########################################################################################################################

# ------------------------------------------------
# Generic Makefile (based on gcc)
#
# ChangeLog :
#	2017-02-10 - Several enhancements + project update mode
#   2015-07-22 - first version
# ------------------------------------------------

######################################
# target
######################################
TARGET = EncoderSimu


######################################
# building variables
######################################
# debug build?
DEBUG = 1
# optimization
OPT = -Og


#######################################
# paths
#######################################
# Build path
BUILD_DIR = build

######################################
# source
######################################


# C sources
C_SOURCES =  \
App/cfgm.c \
App/menu.c \
App/encoder_simu.c \
porting/u8g2/u8g2_porting_ssd1306.c \
thirdparty/u8g2/mui.c \
thirdparty/u8g2/mui_u8g2.c \
thirdparty/u8g2/u8g2_bitmap.c \
thirdparty/u8g2/u8g2_box.c \
thirdparty/u8g2/u8g2_buffer.c \
thirdparty/u8g2/u8g2_button.c \
thirdparty/u8g2/u8g2_circle.c \
thirdparty/u8g2/u8g2_cleardisplay.c \
thirdparty/u8g2/u8g2_d_memory.c \
thirdparty/u8g2/u8g2_d_setup.c \
thirdparty/u8g2/u8g2_font.c \
thirdparty/u8g2/u8g2_fonts.c \
thirdparty/u8g2/u8g2_hvline.c \
thirdparty/u8g2/u8g2_input_value.c \
thirdparty/u8g2/u8g2_intersection.c \
thirdparty/u8g2/u8g2_kerning.c \
thirdparty/u8g2/u8g2_line.c \
thirdparty/u8g2/u8g2_ll_hvline.c \
thirdparty/u8g2/u8g2_message.c \
thirdparty/u8g2/u8g2_polygon.c \
thirdparty/u8g2/u8g2_selection_list.c \
thirdparty/u8g2/u8g2_setup.c \
thirdparty/u8g2/u8log.c \
thirdparty/u8g2/u8log_u8g2.c \
thirdparty/u8g2/u8log_u8x8.c \
thirdparty/u8g2/u8x8_8x8.c \
thirdparty/u8g2/u8x8_byte.c \
thirdparty/u8g2/u8x8_cad.c \
thirdparty/u8g2/u8x8_capture.c \
thirdparty/u8g2/u8x8_debounce.c \
thirdparty/u8g2/u8x8_display.c \
thirdparty/u8g2/u8x8_d_ssd1306_128x64_noname.c \
thirdparty/u8g2/u8x8_fonts.c \
thirdparty/u8g2/u8x8_gpio.c \
thirdparty/u8g2/u8x8_input_value.c \
thirdparty/u8g2/u8x8_message.c \
thirdparty/u8g2/u8x8_selection_list.c \
thirdparty/u8g2/u8x8_setup.c \
thirdparty/u8g2/u8x8_string.c \
thirdparty/u8g2/u8x8_u16toa.c \
thirdparty/u8g2/u8x8_u8toa.c \
thirdparty/ulog/ulog.c \
thirdparty/button/button.c \
Core/Src/main.c \
Core/Src/stm32g0xx_it.c \
Core/Src/stm32g0xx_hal_msp.c \
Core/Src/gpio.c \
Core/Src/usart.c \
Core/Src/stm32g0xx_hal_timebase_tim.c \
Core/Src/spi.c \
Core/Src/tim.c \
Drivers/STM32G0xx_HAL_Driver/Src/stm32g0xx_hal_spi.c \
Drivers/STM32G0xx_HAL_Driver/Src/stm32g0xx_hal_spi_ex.c \
Drivers/STM32G0xx_HAL_Driver/Src/stm32g0xx_hal_rcc.c \
Drivers/STM32G0xx_HAL_Driver/Src/stm32g0xx_hal_rcc_ex.c \
Drivers/STM32G0xx_HAL_Driver/Src/stm32g0xx_ll_rcc.c \
Drivers/STM32G0xx_HAL_Driver/Src/stm32g0xx_hal_flash.c \
Drivers/STM32G0xx_HAL_Driver/Src/stm32g0xx_hal_flash_ex.c \
Drivers/STM32G0xx_HAL_Driver/Src/stm32g0xx_hal_gpio.c \
Drivers/STM32G0xx_HAL_Driver/Src/stm32g0xx_hal_dma.c \
Drivers/STM32G0xx_HAL_Driver/Src/stm32g0xx_hal_dma_ex.c \
Drivers/STM32G0xx_HAL_Driver/Src/stm32g0xx_ll_dma.c \
Drivers/STM32G0xx_HAL_Driver/Src/stm32g0xx_hal_pwr.c \
Drivers/STM32G0xx_HAL_Driver/Src/stm32g0xx_hal_pwr_ex.c \
Drivers/STM32G0xx_HAL_Driver/Src/stm32g0xx_hal_cortex.c \
Drivers/STM32G0xx_HAL_Driver/Src/stm32g0xx_hal.c \
Drivers/STM32G0xx_HAL_Driver/Src/stm32g0xx_hal_exti.c \
Drivers/STM32G0xx_HAL_Driver/Src/stm32g0xx_hal_tim.c \
Drivers/STM32G0xx_HAL_Driver/Src/stm32g0xx_hal_tim_ex.c \
Drivers/STM32G0xx_HAL_Driver/Src/stm32g0xx_hal_uart.c \
Drivers/STM32G0xx_HAL_Driver/Src/stm32g0xx_hal_uart_ex.c \
Core/Src/system_stm32g0xx.c

# ASM sources
ASM_SOURCES =  \
startup_stm32g030xx.s


#######################################
# binaries
#######################################
PREFIX = arm-none-eabi-
# The gcc compiler bin path can be either defined in make command via GCC_PATH variable (> make GCC_PATH=xxx)
# either it can be added to the PATH environment variable.
ifdef GCC_PATH
CC = $(GCC_PATH)/$(PREFIX)gcc
AS = $(GCC_PATH)/$(PREFIX)gcc -x assembler-with-cpp
CP = $(GCC_PATH)/$(PREFIX)objcopy
SZ = $(GCC_PATH)/$(PREFIX)size
else
CC = $(PREFIX)gcc
AS = $(PREFIX)gcc -x assembler-with-cpp
CP = $(PREFIX)objcopy
SZ = $(PREFIX)size
endif
HEX = $(CP) -O ihex
BIN = $(CP) -O binary -S
 
#######################################
# CFLAGS
#######################################
# cpu
CPU = -mcpu=cortex-m0plus

# fpu
# NONE for Cortex-M0/M0+/M3

# float-abi


# mcu
MCU = $(CPU) -mthumb $(FPU) $(FLOAT-ABI)

# macros for gcc
# AS defines
AS_DEFS = 

# C defines
C_DEFS =  \
-DUSE_HAL_DRIVER \
-DSTM32G030xx

AS_INCLUDES = 

# C includes
C_INCLUDES =  \
-ICore/Inc \
-IApp/ \
-Iporting/u8g2/ \
-Ithirdparty/u8g2/ \
-Ithirdparty/ulog/ \
-Ithirdparty/button/ \
-IDrivers/STM32G0xx_HAL_Driver/Inc \
-IDrivers/STM32G0xx_HAL_Driver/Inc/Legacy \
-IDrivers/CMSIS/Device/ST/STM32G0xx/Include \
-IDrivers/CMSIS/Include


# compile gcc flags
ASFLAGS = $(MCU) $(AS_DEFS) $(AS_INCLUDES) $(OPT) -Wall -fdata-sections -ffunction-sections

CFLAGS = $(MCU) $(C_DEFS) $(C_INCLUDES) $(OPT) -Wall -fdata-sections -ffunction-sections

ifeq ($(DEBUG), 1)
CFLAGS += -g -gdwarf-2
endif


# Generate dependency information
CFLAGS += -MMD -MP -MF"$(@:%.o=%.d)"


#######################################
# LDFLAGS
#######################################
# link script
LDSCRIPT = STM32G030K6Tx_FLASH.ld

# libraries
LIBS = -lc -lm -lnosys 
LIBDIR = 
LDFLAGS = $(MCU) -specs=nano.specs -T$(LDSCRIPT) $(LIBDIR) $(LIBS) -Wl,-Map=$(BUILD_DIR)/$(TARGET).map,--cref -Wl,--gc-sections

# default action: build all
all: $(BUILD_DIR)/$(TARGET).elf $(BUILD_DIR)/$(TARGET).hex $(BUILD_DIR)/$(TARGET).bin


#######################################
# build the application
#######################################
# list of objects
OBJECTS = $(addprefix $(BUILD_DIR)/,$(notdir $(C_SOURCES:.c=.o)))
vpath %.c $(sort $(dir $(C_SOURCES)))
# list of ASM program objects
OBJECTS += $(addprefix $(BUILD_DIR)/,$(notdir $(ASM_SOURCES:.s=.o)))
vpath %.s $(sort $(dir $(ASM_SOURCES)))

$(BUILD_DIR)/%.o: %.c Makefile | $(BUILD_DIR) 
	$(CC) -c $(CFLAGS) -Wa,-a,-ad,-alms=$(BUILD_DIR)/$(notdir $(<:.c=.lst)) $< -o $@

$(BUILD_DIR)/%.o: %.s Makefile | $(BUILD_DIR)
	$(AS) -c $(CFLAGS) $< -o $@

$(BUILD_DIR)/$(TARGET).elf: $(OBJECTS) Makefile
	$(CC) $(OBJECTS) $(LDFLAGS) -o $@
	$(SZ) $@

$(BUILD_DIR)/%.hex: $(BUILD_DIR)/%.elf | $(BUILD_DIR)
	$(HEX) $< $@
	
$(BUILD_DIR)/%.bin: $(BUILD_DIR)/%.elf | $(BUILD_DIR)
	$(BIN) $< $@	
	
$(BUILD_DIR):
	mkdir $@		

#######################################
# clean up
#######################################
clean:
	-rm -fR $(BUILD_DIR)
  
#######################################
# install
#######################################
install:
	openocd -f interface/stlink.cfg -f target/stm32g0x.cfg -c "program $(BUILD_DIR)/$(TARGET).elf verify reset exit"

#######################################
# dependencies
#######################################
-include $(wildcard $(BUILD_DIR)/*.d)

# *** EOF ***
